[build]
  command = "npm install && ng build --configuration production"
  publish = "dist/shebew/browser"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    cache-control = '''
    public,
    max-age=31536000'''
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
